import Link from 'next/link';
import JsonLd from '@/components/JsonLd';
import { breadcrumbSchema, faqSchema, pageMetadata } from '@/lib/seo';

const faqs=[
  ['What is an ABC fire extinguisher?','An ABC dry-chemical extinguisher is a multipurpose portable unit intended for Class A ordinary combustibles, Class B flammable liquids, and Class C flammable gases where its rating and local requirements permit. Equipment selection should follow a competent site risk assessment.'],
  ['Which fire extinguisher should I use?','Choose by fire risk, fuel type, electrical involvement, occupancy, applicable standards, and manufacturer rating. Water is not suitable for energized electrical or flammable-liquid fires. A qualified fire-safety professional should confirm selection and placement.'],
  ['How often should extinguishers be serviced?','Perform routine visual checks and arrange professional maintenance at intervals required by applicable Indian standards, manufacturer instructions, site conditions, and the authority having jurisdiction. Record every inspection and service.'],
  ['What is included in a fire-safety AMC?','An AMC can include scheduled inspections, functional testing, preventive maintenance, refilling coordination, asset registers, compliance reports, staff guidance, and priority response. Scope varies by system and plan.'],
  ['How do I request a quotation?','Browse the product catalog, add required items and quantities to the inquiry cart, then download a preliminary PDF or send the inquiry through WhatsApp. For installations or AMC, submit the relevant site form.'],
];
export const metadata=pageMetadata({title:'Fire Safety Guide: Extinguishers, Selection & Maintenance',description:'Practical answers about fire extinguisher types, equipment selection, maintenance schedules, AMC coverage, and requesting quotations in India.',path:'/fire-safety-guide',keywords:['fire extinguisher guide India','which fire extinguisher to use','fire extinguisher maintenance','fire safety AMC guide']});
export default function GuidePage(){return <main className="knowledge-page"><JsonLd data={[breadcrumbSchema([{name:'Home',path:'/'},{name:'Fire Safety Guide',path:'/fire-safety-guide'}]),faqSchema(faqs)]}/><header className="knowledge-hero"><div className="container-narrow"><p className="eyebrow">Fire safety knowledge</p><h1>Clear answers for selecting and maintaining fire-safety equipment.</h1><p>This educational guide explains common product categories and maintenance decisions. Final equipment selection must be based on a competent site assessment and applicable regulations.</p></div></header><div className="container-narrow knowledge-content"><nav aria-label="On this page" className="knowledge-toc"><strong>On this page</strong><a href="#extinguishers">Extinguisher comparison</a><a href="#amc">AMC coverage</a><a href="#faq">Common questions</a></nav><section id="extinguishers"><h2>Fire extinguisher types at a glance</h2><div className="table-scroll"><table><caption>General extinguisher-media comparison. Always verify the product fire rating.</caption><thead><tr><th>Medium</th><th>Typical applications</th><th>Important consideration</th></tr></thead><tbody><tr><th>ABC dry chemical</th><td>Multipurpose coverage for many common commercial risks</td><td>Powder residue can affect sensitive equipment</td></tr><tr><th>Carbon dioxide</th><td>Electrical equipment and certain flammable-liquid risks</td><td>Limited cooling and confined-space considerations</td></tr><tr><th>Foam</th><td>Selected Class A and flammable-liquid risks</td><td>Suitability around electricity must be verified</td></tr><tr><th>Water</th><td>Selected ordinary combustible materials</td><td>Never use on energized electrical or incompatible liquid fires</td></tr></tbody></table></div></section><section id="amc"><h2>What a professional AMC can cover</h2><ul><li>Asset identification and equipment-condition checks</li><li>Scheduled preventive inspection and functional testing</li><li>Refilling, pressure-test, repair, and replacement coordination</li><li>Maintenance records and compliance documentation</li><li>Recommendations for damaged, expired, or unsuitable equipment</li><li>Priority support based on the contracted service level</li></ul><p><Link href="/amc">Compare AMC service options and request an assessment →</Link></p></section><section id="faq"><h2>Frequently asked fire-safety questions</h2>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section><aside className="knowledge-cta"><h2>Need a site-specific recommendation?</h2><p>Share the premises type, floor area, existing systems, and required quantity with our Vellore team.</p><div><Link className="btn btn-primary" href="/contact">Request consultation</Link><Link className="btn btn-secondary" href="/products">Browse equipment</Link></div></aside></div></main>;}
